#ifndef __CONFIG_H__
#define __CONFIG_H__

// #define DEBUG

// #define LOAD_ADDRESS 0x98000000

#define MEMORY_SCELIBC_MB 8
#define MEMORY_NEWLIB_MB 232

#define DATA_PATH "ux0:data/gtasa"
#define SO_PATH DATA_PATH "/" "libGTASA.so"
#define SHADER_CACHE_PATH DATA_PATH "/" "cache"
#define CONFIG_PATH DATA_PATH "/" "config.txt"
#define CONTROLLER_CONFIG_PATH DATA_PATH "/" "controls.txt"

#define SCREEN_W 960
#define SCREEN_H 544

typedef enum {
  MAPPING_UNKNOWN = 0,
  MAPPING_ATTACK,
  MAPPING_SPRINT,
  MAPPING_JUMP,
  MAPPING_CROUCH,
  MAPPING_ENTER_CAR,
  MAPPING_BRAKE,
  MAPPING_HANDBRAKE,
  MAPPING_ACCELERATE,
  MAPPING_CAMERA_CLOSER,
  MAPPING_CAMERA_FARTHER,
  MAPPING_HORN,
  MAPPING_RADIO_PREV_STATION,
  MAPPING_RADIO_NEXT_STATION,
  MAPPING_VITAL_STATS,
  MAPPING_NEXT_WEAPON,
  MAPPING_PREV_WEAPON,
  MAPPING_RADAR,
  MAPPING_PED_LOOK_BACK,
  MAPPING_VEHICLE_LOOK_LEFT,
  MAPPING_VEHICLE_LOOK_RIGHT,
  MAPPING_VEHICLE_LOOK_BACK,
  MAPPING_MISSION_START_AND_CANCEL,
  MAPPING_MISSION_START_AND_CANCEL_VIGILANTE,
  MAPPING_VEHICLE_STEER_X,
  MAPPING_VEHICLE_STEER_Y,
  MAPPING_VEHICLE_STEER_LEFT,
  MAPPING_VEHICLE_STEER_RIGHT,
  MAPPING_LOOK_X,
  MAPPING_LOOK_Y,
  MAPPING_PED_MOVE_X,
  MAPPING_PED_MOVE_Y,
  MAPPING_AUTO_HYDRAULICS,
  MAPPING_SWAP_WEAPONS_AND_PURCHASE,
  MAPPING_WEAPON_ZOOM_IN,
  MAPPING_WEAPON_ZOOM_OUT,
  MAPPING_ENTER_AND_EXIT_TARGETING,
  MAPPING_VEHICLE_BOMB,
  MAPPING_TURRET_LEFT,
  MAPPING_TURRET_RIGHT,
  MAPPING_MAGNET,
  MAPPING_SKIP_CUTSCENE,
  MAPPING_GANG_RECRUIT,
  MAPPING_GANG_IGNORE,
  MAPPING_GANG_FOLLOW,
  MAPPING_GANG_HOLD_POSITION,
  MAPPING_RHYTHM_UP,
  MAPPING_RHYTHM_DOWN,
  MAPPING_RHYTHM_LEFT,
  MAPPING_RHYTHM_RIGHT,
  MAPPING_DROP_CRANE,
  MAPPING_DROP_ITEM,
  MAPPING_PHONE,
  MAPPING_NITRO,
  MAPPING_CRANE_UP,
  MAPPING_CRANE_DOWN,
  MAPPING_ACCEPT,
  MAPPING_CANCEL,
  MAPPING_GRAB,
  MAPPING_STINGER,
  MAPPING_MENU_DOWN,
  MAPPING_MENU_UP,
  MAPPING_MENU_LEFT,
  MAPPING_MENU_RIGHT,
  MAPPING_MENU_ACCEPT,
  MAPPING_MENU_BACK,
  MAPPING_MENU_MAP,
  MAPPING_ARCADE_BUTTON,
  MAPPING_ARCADE_POWER_OFF,
  MAPPING_ARCADE_RESET,
  MAPPING_ARCADE_JOYSTICK,
  MAPPING_GYM_ACTION,
  MAPPING_GYM_EASIER_LEVEL,
  MAPPING_GYM_HARDER_LEVEL,
  MAPPING_BLACK_JACK_SPLIT,
  MAPPING_BLACK_JACK_DOUBLE,
  MAPPING_BLACK_JACK_HIT,
  MAPPING_BLACK_JACK_STAND,
  MAPPING_PLACE_BET,
  MAPPING_REMOVE_BET,
  MAPPING_NEXT_TARGET,
  MAPPING_PREV_TARGET,
  MAPPING_WAYPOINT_BLIP,
  MAPPING_HELICOPTER_MAGNET_UP,
  MAPPING_HELICOPTER_MAGNET_DOWN,
  MAPPING_LOCK_HYDRAULICS,
  MAPPING_FLIGHT_ASCEND,
  MAPPING_FLIGHT_DESCEND,
  MAPPING_FLIGHT_PRIMARY_ATTACK,
  MAPPING_FLIGHT_SECONDARY_ATTACK,
  MAPPING_FLIGHT_ALT_LEFT,
  MAPPING_FLIGHT_ALT_RIGHT,
  MAPPING_FLIGHT_ALT_UP,
  MAPPING_FLIGHT_ALT_DOWN,
  MAPPING_BASKETBALL_SHOOT,
  MAPPING_BUNNY_HOP,
  MAPPING_MAP_ZOOM_IN,
  MAPPING_MAP_ZOOM_OUT,
  MAPPING_ALT_ATTACK,
  MAPPING_BLOCK,
  MAPPING_TAKE_COVER_LEFT,
  MAPPING_TAKE_COVER_RIGHT,
  MAPPING_TOGGLE_LANDING_GEAR,
  MAPPING_KISS,
  MAPPING_DANCING_UP,
  MAPPING_DANCING_DOWN,
  MAPPING_DANCING_LEFT,
  MAPPING_DANCING_RIGHT,
  MAPPING_REPLAY,
  NUM_BUTTON_MAPPING,
} HIDMapping;

typedef enum {
  widget_enter_car,
  widget_attack,
  widget_accelerate,
  widget_brake,
  widget_handbrake,
  UNKNOWN_5,
  UNKNOWN_6,
  widget_horn,
  widget_phone,
  UNKNOWN_9,
  widget_kiss,
  UNKNOWN_11,
  widget_hydraulics,
  widget_auto_hydraulics,
  widget_drop_crane,
  widget_drop_item,
  widget_vehicle_shoot_left,
  widget_vehicle_shoot_right,
  widget_camera,
  widget_enter_targeting,
  UNKNOWN_20,
  widget_vc_shoot,
  UNKNOWN_22,
  widget_air_gun,
  widget_rocket,
  widget_vehicle_bomb,
  widget_vehicle_turret_left,
  widget_vehicle_turret_right,
  widget_purchase,
  widget_swap_weapons,
  widget_nitro,
  UNKNOWN_31,
  UNKNOWN_32,
  widget_button_dive,
  UNKNOWN_34,
  UNKNOWN_35,
  UNKNOWN_36,
  widget_arcade_button,
  widget_arcade_power_off,
  widget_arcade_reset,
  widget_arcade_joystick,
  widget_skip_cutscene,
  widget_train_next_station,
  widget_tap_meter_button,
  widget_crane_up,
  widget_crane_down,
  widget_helicopter_magnet_up,
  widget_helicopter_magnet_down,
  widget_gym_easier,
  widget_gym_harder,
  widget_zoom_in,
  widget_zoom_out,
  widget_race_left,
  widget_race_right,
  widget_store_accept,
  widget_store_cancel,
  widget_store_back,
  widget_store_buy,
  widget_roulette_up,
  widget_roulette_down,
  widget_roulette_left,
  widget_roulette_right,
  widget_place_bet,
  widget_remove_bet,
  UNKNOWN_64,
  UNKNOWN_65,
  widget_grab,
  widget_magnet,
  widget_stinger,
  widget_mission_start,
  widget_mission_start_vigilante,
  widget_mission_cancel,
  widget_mission_cancel_vigilante,
  widget_minigame_start,
  widget_minigame_cancel,
  widget_school_exit,
  widget_school_left,
  widget_school_right,
  UNKNOWN_78,
  widget_school_continue,
  UNKNOWN_80,
  UNKNOWN_81,
  UNKNOWN_82,
  UNKNOWN_83,
  UNKNOWN_84,
  UNKNOWN_85,
  UNKNOWN_86,
  widget_basketball_shoot,
  UNKNOWN_88,
  widget_gambling_quit,
  widget_gambling_continue,
  widget_black_jack_split,
  widget_black_jack_double,
  widget_black_jack_hit,
  widget_black_jack_stand,
  UNKNOWN_95,
  UNKNOWN_96,
  UNKNOWN_97,
  UNKNOWN_98,
  UNKNOWN_99,
  UNKNOWN_100,
  UNKNOWN_101,
  widget_rhythm_exit,
  UNKNOWN_103,
  UNKNOWN_104,
  UNKNOWN_105,
  widget_gang_recruit,
  UNKNOWN_107,
  widget_gang_follow,
  widget_gang_hold,
  widget_reply_yes,
  widget_reply_no,
  UNKNOWN_112,
  UNKNOWN_113,
  UNKNOWN_114,
  UNKNOWN_115,
  UNKNOWN_116,
  UNKNOWN_117,
  UNKNOWN_118,
  UNKNOWN_119,
  UNKNOWN_120,
  UNKNOWN_121,
  UNKNOWN_122,
  UNKNOWN_123,
  UNKNOWN_124,
  UNKNOWN_125,
  UNKNOWN_126,
  UNKNOWN_127,
  UNKNOWN_128,
  UNKNOWN_129,
  UNKNOWN_130,
  UNKNOWN_131,
  UNKNOWN_132,
  UNKNOWN_133,
  widget_video_poker_exit,
  UNKNOWN_135,
  UNKNOWN_136,
  UNKNOWN_137,
  UNKNOWN_138,
  UNKNOWN_139,
  UNKNOWN_140,
  UNKNOWN_141,
  UNKNOWN_142,
  UNKNOWN_143,
  UNKNOWN_144,
  UNKNOWN_145,
  UNKNOWN_146,
  UNKNOWN_147,
  UNKNOWN_148,
  widget_itb_exit,
  UNKNOWN_150,
  UNKNOWN_151,
  UNKNOWN_152,
  UNKNOWN_153,
  UNKNOWN_154,
  UNKNOWN_155,
  UNKNOWN_156,
  UNKNOWN_157,
  UNKNOWN_158,
  UNKNOWN_159,
  widget_player_info,
  widget_radar,
  UNKNOWN_162,
  UNKNOWN_163,
  widget_thumb_circle,
  UNKNOWN_165,
  widget_swipe_radio_down = 166,
  widget_swipe_radio_up = 166,
  widget_ped_move = 167,
  widget_ped_move_down = 167,
  widget_ped_move_left = 167,
  widget_ped_move_right = 167,
  widget_ped_move_up = 167,
  UNKNOWN_168,
  UNKNOWN_169,
  UNKNOWN_170,
  UNKNOWN_171,
  UNKNOWN_172,
  UNKNOWN_173,
  UNKNOWN_174,
  widget_look_left = 175,
  widget_look_right = 175,
  UNKNOWN_176,
  UNKNOWN_177,
  UNKNOWN_178,
  UNKNOWN_179,
  UNKNOWN_180,
  UNKNOWN_181,
  UNKNOWN_182,
  UNKNOWN_183,
  UNKNOWN_184,
  UNKNOWN_185,
  UNKNOWN_186,
  UNKNOWN_187,
  UNKNOWN_188,
  UNKNOWN_189,
} m_pWidgets;

typedef enum {
  BUTTON_UNUSED = -1,
  BUTTON_CROSS = 0,
  BUTTON_CIRCLE = 1,
  BUTTON_SQUARE = 2,
  BUTTON_TRIANGLE = 3,
  BUTTON_START = 4,
  BUTTON_SELECT = 5,
  BUTTON_L1 = 6,
  BUTTON_R1 = 7,
  DPAD_UP = 8,
  DPAD_DOWN = 9,
  DPAD_LEFT = 10,
  DPAD_RIGHT = 11,
  BUTTON_L3 = 12,
  BUTTON_R3 = 13,
  ANALOG_LEFT_X = 64,
  ANALOG_LEFT_Y = 65,
  ANALOG_RIGHT_X = 66,
  ANALOG_RIGHT_Y = 67,
  BUTTON_L2 = 68,
  BUTTON_R2 = 69,
} ButtonID;

#define MAX_BUTTON_MAPPING 128

typedef struct {
  HIDMapping hid_mapping;
  ButtonID button_id;
} ButtonMapping;

typedef enum {
  SKYGFX_COLOR_FILTER_MOBILE,
  SKYGFX_COLOR_FILTER_NONE,
  SKYGFX_COLOR_FILTER_PS2,
  SKYGFX_COLOR_FILTER_PC,
} SkyGfxColorFilter;

typedef struct {
  int touch_x_margin;
  int front_touch_triggers;
  int enable_bones_optimization;
  int enable_mvp_optimization;
  int ignore_mobile_stuff;
  int fix_heli_plane_camera;
  int fix_skin_weights;
  int fix_map_bottleneck;
  int use_shader_cache;
  int skygfx_ps2_shading; // lighting and vehicle reflections
  int skygfx_colorfilter;
  int skygfx_ps2_sun;
  int enable_high_detail_player;
  int disable_detail_textures;
  int disable_ped_spec;
  int disable_tex_bias;
  int disable_mipmaps;
  int aa_mode;
} Config;

extern int mapping_count;
extern ButtonMapping button_mapping[MAX_BUTTON_MAPPING];
extern Config config;

int read_config(const char *file);
int read_controller_config(const char *file);

#endif
